### ISSUE TITLE
Wont connect to linux USB3.0

### ISSUE THREAD

**Issue by NickNunno** [sonyccd/roboclaw_ros#12]
Mode: 7 (packet serial 0x80-128)
Option: 6 (115200 Baud)

Roboclaw FW: 4.1.23
Ubuntu 16.04lts
ROS Kinetic

**Comment by AngelCrusher** [comment]
Working fine here on usb3 - Ubuntu 16.04 on Lenovo laptop nothing special done? What board are you running?
