### ISSUE TITLE
I just damaged my new roboclaw 2x45A controller by launching this file

### ISSUE THREAD

**Issue by ozgurerbulan** [sonyccd/roboclaw_ros#4]
It is useless now and here is what I did,

I have opened the windows app and limited the max I to 50 for protection.
Checked P I D parameters. They were all 0.
Then cloned the repo.
Connected the computer via usb.
Started roslaunch roboclaw_node roboclaw.launch
Firstly motor 1 started to run in full pwm,
Then motor 2 started to run in full pwm and instantly changed direction
Because of the inertia, the controller died even Motors were in neutral.
It was the weirdest thing that I have experience. No idea what the launch file did.
There was not encoders only motors without touching ground.

Anyway, does anybody know why? I have just buy a 2x60A roboclaw and I certainly do not want to damage this one too.

**Comment by sonyccd** [comment]
Wooooooo your PID was set to 0 ?!

**Comment by ozgurerbulan** [comment]
Yep, I was trying to connections without any move. So I thought 0 pid gives no motion. What do you think, what was wrong?

**Comment by sonyccd** [comment]
You have several problems:  

1. You have to have the encoders hooked up or the roboclaw has no way to know how fast the wheels are spinning. For the ROS driver to work that is needed.

2. PID does not work that way, read this for more information. [PID](https://en.wikipedia.org/wiki/PID_controller)  

3. **YOU MUST** tune the PID loop using the software as I stated in the README for the ROS code to work or things like you described will happen.

**Comment by ozgurerbulan** [comment]
I know how PID works. What do you expect when you give zero to P I D coefficients? Well, I expect no motion. As I said before, I set that parameters to zero for not to damage controller in the first launch.

**Comment by sonyccd** [comment]
The ROS driver does not do anything but set speeds for the roboclaw controller to meet.  If it is not properly configured it will not work. This means you must have the encoders attached.  Also if you are just testing I would recommend to disconnect the motors from the power terminals and measure the voltage to see if things are operating properly.

**Comment by harryman1** [comment]
agreed with Sonyccd, I have tested with all the proser connections to the encoders and setup the right values on the Windows application provided by ionmc, when you setup the correct values ans test the node it does work.

I had followed all the recommendations and also did a auto tune, but in my case I did setup and test with low revolutions and thermo fused connections to the motors

the node work very well and does not burn your motor controller :), the only isseu is the odom data

but it works :)
